# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cc009270279c4aa19cbb98e1031258ca6f56116b63002f22875454c5995f1cb3bbbd2eb4ab3d9ec4394fa1bfbb35be61bb39da1fdee4b18a712bdc15f33107a

test:
  secret_key_base: 2894d6b559ccc8f379dd617e707cdfc0227e1855b1380016dee2d1db1ce42007ed648abccb73b9096ad02a719ff7e05f2ddf32c5bad1e21555d85044329a45d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
